#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WhiteLabelAndroid.Resource", IsApplication=true)]

namespace WhiteLabelAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_lock_power_off = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int button_get_children = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int button_get_item = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int button_get_item_by_id = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int button_get_item_by_path = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int button_use = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int field_item = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int instance_database = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int instance_login = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int instance_password = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int instance_site = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int instance_url = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int label = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int settings = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SimpleItemLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int key_database = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int key_instance_url = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int key_login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int key_password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int key_site = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int text_default_database = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int text_default_instance_url = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int text_default_login = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int text_default_password = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int text_default_site = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int text_get_item_by_id = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int text_get_item_by_path = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int text_settings = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
