#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WhiteLabelAndroid.Resource", IsApplication=true)]

namespace WhiteLabelAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_lock_power_off = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int button_create_item = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int button_download = 2131099657;
			
			// aapt resource value: 0x7f06001f
			public const int button_get_item = 2131099679;
			
			// aapt resource value: 0x7f060005
			public const int button_update_created_item = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int button_use = 2131099665;
			
			// aapt resource value: 0x7f06001e
			public const int checkbox_scope_children = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int checkbox_scope_parent = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int checkbox_scope_self = 2131099677;
			
			// aapt resource value: 0x7f06000b
			public const int container_buttons = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int container_item = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int container_item_field = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int container_payload = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int container_scope = 2131099675;
			
			// aapt resource value: 0x7f06000a
			public const int downloaded_image = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int field_image_height = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int field_image_width = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int field_item = 2131099648;
			
			// aapt resource value: 0x7f060015
			public const int field_item_field = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int field_item_name = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int field_item_path = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int field_item_text_field_value = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int field_item_title_field_name = 2131099650;
			
			// aapt resource value: 0x7f060017
			public const int group_payload_type = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int instance_database = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int instance_login = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int instance_password = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int instance_site = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int instance_url = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int items_list = 2131099680;
			
			// aapt resource value: 0x7f060013
			public const int label = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int payload_content = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int payload_full = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int payload_min = 2131099672;
			
			// aapt resource value: 0x7f060021
			public const int settings = 2131099681;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_create_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_download_image = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_settings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SimpleItemLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040023
			public const int hint_database = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int hint_instance_url = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int hint_item_id = 2130968606;
			
			// aapt resource value: 0x7f040026
			public const int hint_item_name = 2130968614;
			
			// aapt resource value: 0x7f040024
			public const int hint_item_parent_id = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hint_item_parent_path = 2130968613;
			
			// aapt resource value: 0x7f04001d
			public const int hint_item_path = 2130968605;
			
			// aapt resource value: 0x7f040028
			public const int hint_item_text_field_value = 2130968616;
			
			// aapt resource value: 0x7f040027
			public const int hint_item_title_field_value = 2130968615;
			
			// aapt resource value: 0x7f040020
			public const int hint_login = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hint_password = 2130968609;
			
			// aapt resource value: 0x7f04001c
			public const int hint_query = 2130968604;
			
			// aapt resource value: 0x7f040022
			public const int hint_site = 2130968610;
			
			// aapt resource value: 0x7f040006
			public const int key_database = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int key_instance_url = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int key_login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int key_password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int key_site = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int menu_text_settings = 2130968577;
			
			// aapt resource value: 0x7f040031
			public const int text_button_download = 2130968625;
			
			// aapt resource value: 0x7f040033
			public const int text_button_get_item = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int text_button_get_item_children = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int text_button_ok = 2130968629;
			
			// aapt resource value: 0x7f040032
			public const int text_button_use = 2130968626;
			
			// aapt resource value: 0x7f040010
			public const int text_create_item_by_id = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int text_create_item_by_path = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int text_default_database = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int text_default_instance_url = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int text_default_login = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int text_default_password = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int text_default_site = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int text_download_image = 2130968591;
			
			// aapt resource value: 0x7f040036
			public const int text_empty_fields_list = 2130968630;
			
			// aapt resource value: 0x7f04002d
			public const int text_empty_id = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int text_empty_path = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int text_empty_query = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int text_error = 2130968618;
			
			// aapt resource value: 0x7f04000c
			public const int text_get_item_by_id = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int text_get_item_by_path = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int text_get_item_by_query = 2130968590;
			
			// aapt resource value: 0x7f040014
			public const int text_height = 2130968596;
			
			// aapt resource value: 0x7f04001b
			public const int text_id_label = 2130968603;
			
			// aapt resource value: 0x7f040030
			public const int text_instance_saved = 2130968624;
			
			// aapt resource value: 0x7f040029
			public const int text_item_received = 2130968617;
			
			// aapt resource value: 0x7f04002e
			public const int text_no_item = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int text_num_of_items_received = 2130968623;
			
			// aapt resource value: 0x7f04001a
			public const int text_path_label = 2130968602;
			
			// aapt resource value: 0x7f040017
			public const int text_payload_content = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int text_payload_full = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int text_payload_min = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int text_payload_title = 2130968597;
			
			// aapt resource value: 0x7f040019
			public const int text_query_label = 2130968601;
			
			// aapt resource value: 0x7f040012
			public const int text_settings_screen = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int text_width = 2130968595;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
