require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "Sitecore.MobileSDK.PCL-1.0.0.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Sitecore Mobile SDK PCL" \
		--summary="Use content Sitecore CMS content in your native mobile apps in C#." \
		--publisher="Sitecore Corporation" \
		--website="http://www.sitecore.net" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/Sitecore_logo_128x128.png" \
		--icon="icons/Sitecore_logo_512x512.png" \
		--library="ios":"bin/Awesome.iOS.dll" \
		--library="android":"bin/Awesome.Android.dll" 
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
