// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace WhiteLabeliOS
{
	public partial class RenderingHtmlViewController : UIViewController
	{
		public RenderingHtmlViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
